language: python
python:
  - 3.6
  - 3.6.1
  - 3.6.2
  - 3.6.3
  - 3.6.4

install:
  - pip install .
  - pip install -r requirements.txt
  - pip install pytest
  - pip install codecov
script:
  - py.test --cov=aiospider --cov-report=term --cov-report=html --cov-append tests

after_success:
  - codecov