language: python
python:
  - 3.6
  - 3.6.1
  - 3.6.2
  - 3.6.3
  - 3.6.4

install:
  - pip install .
  - pip install -r requirements.txt
  - pip install codecov
script:
  - python3 tests/test.py

after_success:
  - codecov